# Generated by Django 4.0.10 on 2025-06-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10)),
                ('content', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=3, default=99.99, max_digits=10)),
            ],
        ),
    ]
